import { ContentItem } from './types';

export const MOCK_CONTENT_ITEMS: ContentItem[] = [
    {
        id: 'item-1',
        title: 'The Desert Runner',
        imageUrl: 'https://via.placeholder.com/300x170/FF0000/FFFFFF?text=Movie+1',
        duration: '2h 15m',
        type: 'Movie',
        contentType: 'Movie',
        metadata: {
            genre: ['Action', 'Adventure'],
            mood: ['Exciting', 'Tense'],
            theme: ['Survival'],
            cast: ['John Smith', 'Jane Doe', 'Chris Evans'],
            audience: ['Teens', 'Adults'],
        },
    },
    {
        id: 'item-2',
        title: 'Cybernetic City',
        duration: '1h 55m',
        type: 'Movie',
        contentType: 'Movie',
        metadata: {
            genre: ['Sci-Fi', 'Thriller'],
            theme: ['Dystopian', 'Technology'],
            mood: ['Dark', 'Suspenseful'],
            cast: ['Peter Jones', 'Ana de Armas', 'Chris Evans'],
            audience: ['Adults'],
        },
    },
    {
        id: 'item-3',
        title: 'The Last Kingdom',
        imageUrl: 'https://via.placeholder.com/300x170/008000/FFFFFF?text=Series+1',
        duration: 'S1 E1 - 50m',
        type: 'Series',
        contentType: 'Show',
        metadata: {
            genre: ['Historical', 'Drama', 'Action'],
            era: ['Viking Age'],
            mood: ['Gritty', 'Epic'],
            cast: ['Alexander Dreymon', 'Emily Cox'],
            audience: ['Adults'],
        },
    },
    {
        id: 'item-4',
        title: 'Comedy Nights',
        imageUrl: 'https://via.placeholder.com/300x170/FFA500/FFFFFF?text=Show+1',
        duration: 'S3 E4 - 22m',
        type: 'Episode',
        contentType: 'Fast Channel',
        metadata: {
            genre: ['Comedy'],
            theme: ['Stand-up'],
            mood: ['Funny', 'Lighthearted'],
            cast: ['Kevin Hart'],
            audience: ['Teens', 'Adults'],
        },
    },
    {
        id: 'item-5',
        title: 'Planet Earth III',
        imageUrl: 'https://via.placeholder.com/300x170/800080/FFFFFF?text=Doc+1',
        duration: '1h 5m',
        type: 'Movie',
        contentType: 'Movie',
        metadata: {
            genre: ['Documentary'],
            theme: ['Nature', 'Wildlife'],
            cast: ['David Attenborough'],
            audience: ['Family', 'Kids'],
        },
    },
    {
        id: 'item-6',
        title: 'Rogue Agent',
        imageUrl: 'https://via.placeholder.com/300x170/800000/FFFFFF?text=Movie+2',
        duration: '1h 45m',
        type: 'Movie',
        contentType: 'Movie',
        metadata: {
            genre: ['Action', 'Thriller'],
            mood: ['Intense', 'Suspenseful'],
            theme: ['Espionage'],
            cast: ['John Smith', 'Ana de Armas'],
            audience: ['Adults'],
        },
    },
    {
        id: 'item-7',
        title: 'Galaxy Quest 2',
        imageUrl: 'https://via.placeholder.com/300x170/0000FF/FFFFFF?text=Movie+3',
        duration: '2h 5m',
        type: 'Movie',
        contentType: 'Movie',
        metadata: {
            genre: ['Sci-Fi', 'Comedy'],
            theme: ['Space', 'Parody'],
            mood: ['Funny', 'Adventurous'],
            cast: ['Tim Allen', 'Sigourney Weaver', 'Peter Jones'],
            audience: ['Family', 'Teens'],
        },
    },
    {
        id: 'item-8',
        title: 'Vikings: Valhalla',
        imageUrl: 'https://via.placeholder.com/300x170/A52A2A/FFFFFF?text=Series+2',
        duration: 'S1 E1 - 55m',
        type: 'Series',
        contentType: 'Show',
        metadata: {
            genre: ['Historical', 'Action'],
            era: ['Viking Age'],
            mood: ['Violent', 'Epic'],
            theme: ['Warfare'],
            cast: ['Sam Corlett', 'Frida Gustavsson', 'Alexander Dreymon'],
            audience: ['Adults'],
        },
    },
    {
        id: 'item-9',
        title: "Ocean's Depths",
        imageUrl: 'https://via.placeholder.com/300x170/00CED1/FFFFFF?text=Doc+2',
        duration: '1h 25m',
        type: 'Movie',
        contentType: 'Movie',
        metadata: {
            genre: ['Documentary', 'Adventure'],
            theme: ['Nature', 'Wildlife'],
            mood: ['Awe-inspiring', 'Calm'],
            cast: ['Morgan Freeman'],
            audience: ['Family'],
        },
    },
    {
        id: 'item-10',
        title: 'Starlight Romance',
        duration: '1h 30m',
        type: 'Movie',
        contentType: 'Movie',
        metadata: {
            genre: ['Romance', 'Comedy'],
            theme: ['Romance'],
            mood: ['Heartwarming', 'Funny'],
            cast: ['Emma Stone', 'Ryan Gosling'],
            audience: ['Teens', 'Adults'],
        },
    },
    {
        id: 'item-11',
        title: 'The Crown',
        imageUrl: 'https://via.placeholder.com/300x170/FFD700/000000?text=Series+3',
        duration: 'S2 E3 - 58m',
        type: 'Series',
        contentType: 'Show',
        metadata: {
            genre: ['Drama', 'Historical'],
            theme: ['Royalty', 'Politics'],
            mood: ['Serious', 'Intriguing'],
            cast: ['Claire Foy', 'Olivia Colman'],
            audience: ['Adults'],
        },
    },
    {
        id: 'item-12',
        title: 'Mind Hack',
        duration: '2h 10m',
        type: 'Movie',
        contentType: 'Movie',
        metadata: {
            genre: ['Sci-Fi', 'Thriller'],
            theme: ['Technology', 'Conspiracy'],
            mood: ['Tense', 'Mind-bending'],
            cast: ['John Smith', 'Zendaya'],
            audience: ['Adults'],
        },
    },
    {
        id: 'item-13',
        title: 'Cartoon Carnival',
        imageUrl: 'https://via.placeholder.com/300x170/32CD32/FFFFFF?text=Kids+1',
        duration: 'S1 E5 - 15m',
        type: 'Series',
        contentType: 'Show',
        metadata: {
            genre: ['Animation', 'Comedy'],
            theme: ['Cartoon'],
            mood: ['Goofy', 'Lighthearted'],
            cast: ['Tom Kenny', 'Tara Strong'],
            audience: ['Kids'],
        },
    },
    {
        id: 'item-14',
        title: 'War Zone Diaries',
        duration: '2h 5m',
        type: 'Movie',
        contentType: 'Movie',
        metadata: {
            genre: ['War', 'Drama'],
            theme: ['Warfare', 'Survival'],
            mood: ['Gritty', 'Emotional'],
            cast: ['Chris Evans', 'Tom Hardy'],
            audience: ['Adults'],
        },
    },
    {
        id: 'item-15',
        title: 'Culinary Kings',
        imageUrl: 'https://via.placeholder.com/300x170/F0E68C/000000?text=Show+2',
        duration: 'S2 E1 - 45m',
        type: 'Episode',
        contentType: 'Shahid Channel',
        metadata: {
            genre: ['Reality'],
            theme: ['Cooking', 'Competition'],
            mood: ['Exciting', 'Competitive'],
            cast: ['Gordon Ramsay'],
            audience: ['Family', 'Teens'],
        },
    },
    {
        id: 'item-16',
        title: "The Alchemist's Secret",
        duration: '1h 50m',
        type: 'Movie',
        contentType: 'Movie',
        metadata: {
            genre: ['Fantasy', 'Adventure'],
            theme: ['Magic', 'Mystery'],
            mood: ['Mysterious', 'Adventurous'],
            cast: ['Ana de Armas', 'Daniel Radcliffe'],
            audience: ['Teens', 'Adults'],
        },
    },
    {
        id: 'item-17',
        title: 'Silent Witness',
        imageUrl: 'https://via.placeholder.com/300x170/708090/FFFFFF?text=Movie+4',
        duration: '1h 35m',
        type: 'Movie',
        contentType: 'Movie',
        metadata: {
            genre: ['Thriller', 'Crime'],
            theme: ['Mystery', 'Investigation'],
            mood: ['Suspenseful', 'Dark'],
            cast: ['Jane Doe', 'Idris Elba'],
            audience: ['Adults'],
        },
    },
    {
        id: 'item-18',
        title: 'Laugh Riot',
        duration: '1h 5m',
        type: 'Movie',
        contentType: 'Episode',
        metadata: {
            genre: ['Comedy'],
            theme: ['Stand-up'],
            mood: ['Funny'],
            cast: ['Dave Chappelle'],
            audience: ['Adults'],
        },
    },
    {
        id: 'item-19',
        title: 'Future Imperfect',
        imageUrl: 'https://via.placeholder.com/300x170/20B2AA/FFFFFF?text=Series+4',
        duration: 'S1 E1 - 48m',
        type: 'Series',
        contentType: 'Show',
        metadata: {
            genre: ['Sci-Fi', 'Drama'],
            theme: ['Dystopian', 'Technology'],
            mood: ['Serious', 'Thought-provoking'],
            cast: ['Peter Jones', 'Emma Watson'],
            audience: ['Teens', 'Adults'],
        },
    },
    {
        id: 'item-20',
        title: 'Lost Treasure of the Amazon',
        duration: '2h 20m',
        type: 'Movie',
        contentType: 'Movie',
        metadata: {
            genre: ['Adventure', 'Action'],
            theme: ['Exploration', 'Treasure Hunt'],
            mood: ['Exciting', 'Adventurous'],
            cast: ['Dwayne Johnson', 'Emily Blunt'],
            audience: ['Family', 'Teens'],
        },
    },
    {
        id: 'item-21',
        title: 'Champions League Final',
        imageUrl: 'https://via.placeholder.com/300x170/1E90FF/FFFFFF?text=Live+Match',
        duration: 'Live',
        type: 'Movie',
        contentType: 'Live Match',
        metadata: {
            genre: ['Sports'],
            theme: ['Soccer', 'Competition'],
            mood: ['Exciting', 'Live'],
            cast: ['Commentator A', 'Commentator B'],
            audience: ['Adults', 'Teens'],
        },
    },
    {
        id: 'item-22',
        title: 'Riyadh Season Concert',
        imageUrl: 'https://via.placeholder.com/300x170/DA70D6/FFFFFF?text=Live+Event',
        duration: 'Live',
        type: 'Movie',
        contentType: 'Live Event',
        metadata: {
            genre: ['Music'],
            theme: ['Concert', 'Live Event'],
            mood: ['Energetic', 'Live'],
            cast: ['Artist X', 'Artist Y'],
            audience: ['Adults', 'Teens'],
        },
    },
];